spring:
  application:
    name: mc-hystrix-dashboard-turbine

server:
  port: 8771

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

turbine:
  app-config: "mc-spc-sales-service"
  aggregator:
    cluster-config: defult
  cluster-name-expression: new String("default")